name: fly_diary_0_0_0
description: A Flutter weather-integrated diary application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+11 # 이미지 피커 플러그인 추가
  # provider 패키지
  provider: ^6.1.3

  intl: ^0.18.1

  # 위치 정보
  geolocator: ^10.1.0

  # HTTP 통신
  http: ^1.2.0

  # 환경 변수(.env) 로딩
  flutter_dotenv: ^5.1.0

  # 달력
  table_calendar: ^3.0.9

  # GetX - 상태 관리, 라우팅, 종속성 주입, 그리고 다양한 유틸리티 기능을 제공
  get: ^4.7.2

  # flutter_quill 패키지 설치: (풍부한 텍스트 편집)
  flutter_quill: ^8.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
